### ISSUE TITLE
'message of undefined' when initializing datatbase with 'node server/initDB.js'

### ISSUE THREAD

**Issue by rigs147** [angular-app/angular-app#224]
Hi,

I am receiving an error when I am initializing the database with an admin user. I have followed all previous steps but the connection looks to be timing out. the error message states : 

'There was an error checking the documents Error: connect ETIMEDOUT. errno: 'ETIMEDOUT', syscall: 'connect'

Type Error: Cannot read property 'message' of undefined

**Comment by jbarros35** [comment]
I have the same problem, can you explain a method to connect locally? This procedure is exaustive and doesn't help much for beginners.
